storage:
    resource: "@StorageBundle/Resources/config/routing.xml"
    prefix:   /

artel_profile:
    resource: "@ArtelProfileBundle/Resources/config/routing.yml"
    prefix:   /pf

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_routing:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login